### PR TITLE
Catches SIGINT and SIGTERM signals and exits gracefully

### PR DESCRIPTION
**Pull request by kirichkov**
Also all known devices are marked as away before exiting

### CODE REVIEW

**Comment by kirichkov** [comment]
@kamaradclimber can you check and merge this? I want to add extra options to demonize the process and to create pid file and possibly logging to file so this can be properly started via systemd/monit/etc.

**Review by kamaradclimber — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing this.

I am ok with the signal trap but disagree with cleaning devices on exit.

Cleaning devices on exit will create unnecessary events for devices that are still present.

What about writing state in a small file on exit and rereading it at startup?

**Comment by kirichkov** [comment]
My logic here is as follows - once the tracker is closed, the state should not be assumed as present. If the tracker is stopped - then there is no way to know whether a device is found or not. It's safer for hass to assume it away, then to be present.

As to writing it in a file - I think that's really overcomplicating it.

**Review by kamaradclimber — APPROVED** [review]

**Comment by kirichkov** [comment]
Thanks for merging!

**Pull request merged**
